/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moteur_physique;

import org.junit.Test;
import static org.junit.Assert.*;

public class QuadrilatereTest{
    @Test public void testIsInTheShape() {
      Position E=new Position(5.65,2.1);
      Position F= new Position(2.23,3.5);
      Position G= new Position(7.87,3.16);
      Quadrilatere r=new Quadrilatere(0.5,new Position(3,2),new Position(3.35,4),new Position(6.49,3.74),new Position(7.21,0.26));
      assertTrue(r.isInTheShape(E));
      assertTrue(!r.isInTheShape(F));
      assertTrue(!r.isInTheShape(G));
    }
}
