/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moteur_physique;

import org.junit.Test;
import static org.junit.Assert.*;

public class TriangleTest{
    @Test public void testIsInTheShape() {
      Position D=new Position(2.46,2.7);
      Position E= new Position(1,3);
      Triangle r=new Triangle(0.5,new Position(1,2),new Position(2,3),new Position(4,3));
       assertTrue(r.isInTheShape(D));
       assertTrue(!r.isInTheShape(E));
    }
}
